version: '3'

services:
  backend-development:
      image: ${APPNAME:-node}:${APPVERSION:-latest}
      build: 
        context: backend-development                                                                   
        dockerfile: ./epic-timesheet-and-leaves-comparison-backend-development.Dockerfile
      ports:
        - "3010:3010"
        
  frontend-development:
      image: ${APPNAME:-node}:${APPVERSION:-latest}
      build: 
        context: frontend-development
        dockerfile: ./epic-timesheet-and-leaves-comparison-frontend-development.Dockerfile                                              
      ports:
        - "3000:3000"
   
