version: '3'

services:
  backend-development:
      
      build: 
        context: ./backend-development/epic-timesheet-and-leaves-comparison-backend-development/                                                                  
         
      ports:
        - "3010:3010"
      volumes: 
        - .:/app
        
  frontend-development:
      
      build: 
        context: ./frontend-development/epic-timesheet-and-leaves-comparison-frontend-development/
      ports:
        - "3000:3000"
        
      volumes: 
        - .:/app  
   
